name: 为了快速解决你遇到的问题, 请使用此模板进行提问
description: 运行autowzry过程遇到的各种问题
title: "[windows][MuMu模拟器][问题描述]"
labels: ["模拟器","对战","礼包","组队","源码运行"]
body:
  - type: checkboxes
    attributes:
      label: "请在完成下面的内容后再进行提问:"
      description: "提问题前先阅读使用文档, 以节省你和我的时间"
      options:
        - label: "🌱已阅读[安装教程]( https://cndaqiang.github.io/wzry.doc/guide/install/ )"
        - label: "🌱已阅读[切换对战模式和礼包的方法]( https://cndaqiang.github.io/wzry.doc/guide/file/ )"
        - label: "🌱已阅读[常见问题]( https://cndaqiang.github.io/wzry.doc/qa/qa )"
  - type: markdown
    attributes:
      value: |
        - 🥰请礼貌**友善**的提问.
        - ✨为本项目点个star, 我会更愉快的回答你的问题.
        - 程序如果可以运行，就可以忽视各种警告和提示.
  - type: textarea
    attributes:
      label: "简单描述你的问题"
      description: "请在此处描述你遇到的问题"
      value: |
        例如,新赛季后，MuMu模拟器的IOS登录方式会封禁账户?
    validations:
      required: true
  - type: textarea
    attributes:
      label: "上传完整的运行日志result.0.txt"
      description: "请在此处上传你的执行结果或截图"
      value: |
        此处支持: 填写文本、上传文件、粘贴截图
    validations:
      required: true
  - type: textarea
    attributes:
      label: "上传配置文件: config.example.yaml"
      description: "请在此处上传你的执行结果或截图"
      value: |
        此处支持: 填写文本、上传文件、粘贴截图
    validations:
      required: true
  - type: textarea
    attributes:
      label: "上传控制文件: WZRY.0.运行模式.txt"
      description: "请在此处填写或上传你的控制文件"
      value: |
        此处支持: 填写文本、上传文件、粘贴截图
    validations:
      required: true
  - type: textarea
    attributes:
      label: "粘贴运行目录截图"
      description: "请截图运行目录并粘贴到此处"
      value: |
        粘贴截图
  - type: textarea
    attributes:
      label: "模拟器设置截图"
      description: "如果问题不涉及模拟器, 可以不填写此输入框."
      value: |
        粘贴截图