name: Upload Python Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the package'
        required: true
        default: '2.1.7'
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare package structure
      run: |
        rm -rf autowzry
        mkdir autowzry
        mv assets __init__.py tiyanfu.py wzry.py wzyd.py autowzry/

    - name: Set version in pyproject.toml
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION="${{ github.ref_name }}"
        else
          VERSION="${{ github.event.inputs.version }}"
        fi
        echo "Version: $VERSION"
        sed -i "s/^version = .*/version = \"$VERSION\" # auto/" pyproject.toml

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
